name: MLOPS CI CD Pipeline

on:
    push:
        branches:
            - main
        
    pull_request:
        branches:
            - main

jobs:
    build-test-train:
        runs-on: ubuntu-latest


        steps:
            # Step 1 Checkout source code
            - name: Checkout repositery
              uses: actions/checkout@v4

            # step 2 Setup python environment
            - name: Setup Python
              uses: actions/setup-python@v5

              with:
                python-version: "3.10"

            
            # step 3 Install dependencies
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            # step 4 Run unit tests
            - name: Run unit tests
              run: pytest -v

            # step 5 Train the Model

            - name: Train model
              run: python src/train.py

            # step 6 Evealuate the model
            - name: Evaluate model
              run: python src/evaluate.py

            # step 7 Upload the train model as artifact
            - name: Upload model artifact
              uses: actions/upload-artifact@v4

              with:
                name: trained-model
                path: models/model.pkl




    deploy:
        needs: build-test-train
        runs-on: ubuntu-latest


        steps:
            # step 8 Download the train model
            - name: Download model artifact
              uses: actions/download-artifact@v4

              with:
                name: trained-model
                path: models

            # step 9 Deployment simulations
            - name: Deployment simulation
              run: |
                echo "Model deployed successfully"
                ls -l models